name: Workflow Divisifieur
on: [push]
jobs:
  build:
    runs-on : ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Checkout 
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Build Gradle
        run: ./gradlew build
        
      - name : Exécution du Divisifieur
        run: java -jar build/libs/*.jar 3 1
      
      - name: Création de l'artéfact 
        uses: actions/upload-artifact@v2
        with:
          name: Création du .jar
          path: build/libs/*.jar
